# Generated by Django 5.0.1 on 2025-11-06 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0016_suggestedhistory_suggestiontemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinician',
            name='specialization',
        ),
        migrations.CreateModel(
            name='ClinicianSpecialization',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancer_type', models.ForeignKey(limit_choices_to={'parent__isnull': True}, on_delete=django.db.models.deletion.PROTECT, related_name='specialization_clinicians', to='data_management.cancertype')),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinician_specializations', to='data_management.clinician')),
            ],
            options={
                'db_table': 'clinician_specializations',
            },
        ),
        migrations.AddField(
            model_name='clinician',
            name='specializations',
            field=models.ManyToManyField(limit_choices_to={'parent__isnull': True}, related_name='clinicians', through='data_management.ClinicianSpecialization', to='data_management.cancertype'),
        ),
        migrations.AddIndex(
            model_name='clinicianspecialization',
            index=models.Index(fields=['clinician'], name='clinician_s_clinici_3bea9b_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicianspecialization',
            index=models.Index(fields=['cancer_type'], name='clinician_s_cancer__143112_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clinicianspecialization',
            unique_together={('clinician', 'cancer_type')},
        ),
    ]
